# name: "hzhaoc"
# description: ""

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 50
paginate_path: /page-:num

disqus-id: hzhaoc

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

